### PR TITLE
Drop interactive mode

### PR DESCRIPTION
**Pull request by Tom32i**
- Gad don't stay "open" after executing one command
- Commands now supports arguments (e.g. `gad changelog --all` to see all issues for the sprint)
- Errors are properly caught

### CODE REVIEW

**Review by chalasr — COMMENTED** [review]
👍  Nice. 
About using `&&` for running several commands, won't this conflict with the native unix `&&`? For instance, running `gad sprint && review && vagrant up` won't work anymore, right?

**Comment by Tom32i** [comment]
@chalasr It's slightly better than that: the `&&` will still be parsed by your terminal by default:

- So `gad sprint && review && vagrant up` would be interpreted as `gad sprint` + `review` + `vagrant up` (and will probably fail because of `review).
- But `gad "sprint && review" && vagrant up` will work as expected.

I you think this do more wrong than right, I'm prepared to remove it.

**Review by ogizanagi — APPROVED** [review]
I'm not sure either about the several commands features. IMHO we should simply leverage on basic shell features for such things.

**Review by chalasr — APPROVED** [review]
Yea I would remove it, that will prevent from wtf moments

**Comment by chalasr** [comment]
Just played a bit with this, the following runs fine: 
`gad -o [org] -r [repo] [command] --[command-options]` 
but the following doesn't: 
`gad [command] -o [org] -r [repo] --[command-options]`
it leads to:

> ⏳  Fetching issues...
 { [Error: Empty value for parameter 'owner': null]
  defaultMessage: 'Bad Request',
  message: 'Empty value for parameter \'owner\': null',
  code: '400',
  status: 'Bad Request',
  headers: undefined }

Firstly, I think we should add some validation rules to the options and validate them before performing any http request or writing anything to the output, in order to provide meaningful error messages when an option is missing or has an invalid value.
The first thing I would validate, now that you removed the interactive mode, is that a valid command has been passed. 
Actually running just `gad` within this PR leads to the very same error (Bad Request, null `owner`). I would love to get an "help" displayed in this case (list of all commands with options, same as the README table)
Running  `gad foobar` leads to the same. I would love to get something like `Invalid command "foobar". [help]` in this case. WDYT?

Secondly, is it expected that global options (e.g. `--owner, --repo`) must be passed before the command name and options? 
I think it would be nice if my 2nd (failing) try had worked as the first one. Is it doable? 
That means kind of merging global options with command ones so that neither their order nor their position matters, which makes sense I think.

**Comment by Tom32i** [comment]
@chalasr I moved your concerns in a [specific issue](https://github.com/Elao/github-agile-dashboard/issues/13).

**Comment by chalasr** [comment]
👌 Merging then

**Pull request merged**
